library(pls)
library(glmnet)
library(xtable)
library(testthat)
library(Matrix)
library(devtools)
library(knitr)
library(shiny)
library(ggplot2)
library(ggmap)
library(lattice)
library(leaflet)
library(RColorBrewer)
library(dplyr)

sink("../../session-info.txt", append = TRUE)
cat("Session Information\n\n")
print(sessionInfo())
devtools::session_info()
sink()
